package poker.model.domain

enum class CardApiCodes(val cardCode: String, val card: Card){
    D2("D2", Card(Suit.DIAMOND, Weight.TWO)),
    D3("D3", Card(Suit.DIAMOND, Weight.THREE)),
    D4("D4", Card(Suit.DIAMOND, Weight.FOUR)),
    D5("D5", Card(Suit.DIAMOND, Weight.FIVE)),
    D6("D6", Card(Suit.DIAMOND, Weight.SIX)),
    D7("D7", Card(Suit.DIAMOND, Weight.SEVEN)),
    D8("D8", Card(Suit.DIAMOND, Weight.EIGHT)),
    D9("D9", Card(Suit.DIAMOND, Weight.NINE)),
    D10("D10", Card(Suit.DIAMOND, Weight.TEN)),
    DJ("DJ", Card(Suit.DIAMOND, Weight.JACK)),
    DQ("DQ", Card(Suit.DIAMOND, Weight.QUEEN)),
    DK("DK", Card(Suit.DIAMOND, Weight.KING)),
    DA("DA", Card(Suit.DIAMOND, Weight.ACE)),
    H2("H2", Card(Suit.HEART, Weight.TWO)),
    H3("H3", Card(Suit.HEART, Weight.THREE)),
    H4("H4", Card(Suit.HEART, Weight.FOUR)),
    H5("H5", Card(Suit.HEART, Weight.FIVE)),
    H6("H6", Card(Suit.HEART, Weight.SIX)),
    H7("H7", Card(Suit.HEART, Weight.SEVEN)),
    H8("H8", Card(Suit.HEART, Weight.EIGHT)),
    H9("H9", Card(Suit.HEART, Weight.NINE)),
    H10("H10", Card(Suit.HEART, Weight.TEN)),
    HJ("HJ", Card(Suit.HEART, Weight.JACK)),
    HQ("HQ", Card(Suit.HEART, Weight.QUEEN)),
    HK("HK", Card(Suit.HEART, Weight.KING)),
    HA("HA", Card(Suit.HEART, Weight.ACE)),
    S2("S2", Card(Suit.SPADE, Weight.TWO)),
    S3("S3", Card(Suit.SPADE, Weight.THREE)),
    S4("S4", Card(Suit.SPADE, Weight.FOUR)),
    S5("S5", Card(Suit.SPADE, Weight.FIVE)),
    S6("S6", Card(Suit.SPADE, Weight.SIX)),
    S7("S7", Card(Suit.SPADE, Weight.SEVEN)),
    S8("S8", Card(Suit.SPADE, Weight.EIGHT)),
    S9("S9", Card(Suit.SPADE, Weight.NINE)),
    S10("S10", Card(Suit.SPADE, Weight.TEN)),
    SJ("SJ", Card(Suit.SPADE, Weight.JACK)),
    SQ("SQ", Card(Suit.SPADE, Weight.QUEEN)),
    SK("SK", Card(Suit.SPADE, Weight.KING)),
    SA("SA", Card(Suit.SPADE, Weight.ACE)),
    C2("C2", Card(Suit.CLUB, Weight.TWO)),
    C3("C3", Card(Suit.CLUB, Weight.THREE)),
    C4("C4", Card(Suit.CLUB, Weight.FOUR)),
    C5("C5", Card(Suit.CLUB, Weight.FIVE)),
    C6("C6", Card(Suit.CLUB, Weight.SIX)),
    C7("C7", Card(Suit.CLUB, Weight.SEVEN)),
    C8("C8", Card(Suit.CLUB, Weight.EIGHT)),
    C9("C9", Card(Suit.CLUB, Weight.NINE)),
    C10("C10", Card(Suit.CLUB, Weight.TEN)),
    CJ("CJ", Card(Suit.CLUB, Weight.JACK)),
    CQ("CQ", Card(Suit.CLUB, Weight.QUEEN)),
    CK("CK", Card(Suit.CLUB, Weight.KING)),
    CA("CA", Card(Suit.CLUB, Weight.ACE));

    companion object {
        fun translateToCard(cardCode: String): Card =
            values().first { it.cardCode == cardCode }.card
    }
}